package oracle.apps.xxon.om.gbw.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwLovAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public XXONGbwLovAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("oracle.apps.xxon.om.gbw.lov.server", /* package name */
      "XXONGbwLovAMLocal" /* Configuration Name */);
    }


    /**Container's getter for XXONGbwOperatingUnitLovVO1
     */
    public XXONGbwOperatingUnitLovVOImpl getXXONGbwOperatingUnitLovVO1() {
        return (XXONGbwOperatingUnitLovVOImpl)findViewObject("XXONGbwOperatingUnitLovVO1");
    }


    /**Container's getter for XXONGbwOpnLovVO1
     */
    public XXONGbwOpnLovVOImpl getXXONGbwOpnLovVO1() {
        return (XXONGbwOpnLovVOImpl)findViewObject("XXONGbwOpnLovVO1");
    }

    /**Container's getter for XXONGbwOmAuditTransactionTypeLovVO1
     */
    public XXONGbwOmAuditTransactionTypeLovVOImpl getXXONGbwOmAuditTransactionTypeLovVO1() {
        return (XXONGbwOmAuditTransactionTypeLovVOImpl)findViewObject("XXONGbwOmAuditTransactionTypeLovVO1");
    }

    /**Container's getter for XXONGbwOmDemandTypeLovVO1
     */
    public XXONGbwOmDemandTypeLovVOImpl getXXONGbwOmDemandTypeLovVO1() {
        return (XXONGbwOmDemandTypeLovVOImpl)findViewObject("XXONGbwOmDemandTypeLovVO1");
    }

    /**Container's getter for XXONGbwOmSchedulingMethodLovVO1
     */
    public XXONGbwOmSchedulingMethodLovVOImpl getXXONGbwOmSchedulingMethodLovVO1() {
        return (XXONGbwOmSchedulingMethodLovVOImpl)findViewObject("XXONGbwOmSchedulingMethodLovVO1");
    }

    /**Container's getter for XXONGbwOmTransactionTypeLovVO1
     */
    public XXONGbwOmTransactionTypeLovVOImpl getXXONGbwOmTransactionTypeLovVO1() {
        return (XXONGbwOmTransactionTypeLovVOImpl)findViewObject("XXONGbwOmTransactionTypeLovVO1");
    }

    /**Container's getter for XXONGbwOmUserLovVO1
     */
    public XXONGbwOmUserLovVOImpl getXXONGbwOmUserLovVO1() {
        return (XXONGbwOmUserLovVOImpl)findViewObject("XXONGbwOmUserLovVO1");
    }
}
