package oracle.apps.xxon.om.gbw.chgord.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwOrderTypeVORowImpl extends OAViewRowImpl {
    public static final int ORDERTYPE = 0;
    public static final int FLEXVALUE = 1;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwOrderTypeVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute OrderType
     */
    public String getOrderType() {
        return (String) getAttributeInternal(ORDERTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderType
     */
    public void setOrderType(String value) {
        setAttributeInternal(ORDERTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute FlexValue
     */
    public String getFlexValue() {
        return (String) getAttributeInternal(FLEXVALUE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FlexValue
     */
    public void setFlexValue(String value) {
        setAttributeInternal(FLEXVALUE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ORDERTYPE:
            return getOrderType();
        case FLEXVALUE:
            return getFlexValue();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ORDERTYPE:
            setOrderType((String)value);
            return;
        case FLEXVALUE:
            setFlexValue((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
