package oracle.apps.xxon.om.gbw.chgord.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwSrchResultVORowImpl extends OAViewRowImpl {
    public static final int OPN = 0;
    public static final int ORDERNUMBER = 1;
    public static final int RSD = 2;
    public static final int SSD = 3;
    public static final int SAD = 4;
    public static final int PLRSD = 5;
    public static final int PLNEWRSD = 6;
    public static final int QUANTITY = 7;
    public static final int HEADERID = 8;
    public static final int LINEID = 9;
    public static final int ORGID = 10;
    public static final int LINENUMBER = 11;
    public static final int CHANGETYPE = 12;
    public static final int NEWRSD = 13;
    public static final int NEWSSD = 14;
    public static final int NEWQUANTITY = 15;
    public static final int STATUS = 16;
    public static final int CUSTCODE = 17;
    public static final int CUST5CODE = 18;
    public static final int ORDERTYPE = 19;
    public static final int ORDERHOLD = 20;
    public static final int LEADTIME = 21;
    public static final int MPQ = 22;
    public static final int PAL = 23;
    public static final int PACKAGE1 = 24;
    public static final int PRODCATEGORY = 25;
    public static final int MAXQTYLEADTIME = 26;
    public static final int STGLINEID = 27;
    public static final int STGHEADERID = 28;
    public static final int DBNQTY = 29;
    public static final int DBNRSD = 30;
    public static final int DBPLRSD = 31;
    public static final int DBPLNEWRSD = 32;
    public static final int INVENTORYITEMID = 33;
    public static final int ORGANIZATIONID = 34;
    public static final int ITEMNUMBER = 35;
    public static final int BIZCLASS = 36;
    public static final int OPERUNIT = 37;
    public static final int ITEMSTATUS = 38;
    public static final int CUSTPONUMBER = 39;
    public static final int CUSTPOLINENUMBER = 40;
    public static final int PRICELIST = 41;
    public static final int PRICELISTSTATUS = 42;
    public static final int CANCELREASON = 43;
    public static final int ISSELECT = 44;
    public static final int DEMANDTYPE = 45;
    public static final int ISREADONLY = 46;
    public static final int DB_NEWSSD = 47;
    public static final int SSDREADONLY = 48;
    public static final int REASONCODE = 49;
    public static final int REASCODEREADONLY = 50;
    public static final int PLANNERID = 51;
    public static final int SITEUSECODE = 52;
    public static final int LEGACYORDER = 53;
    public static final int LEGACYLINENUMBER = 54;
    public static final int SSDRESCEDULECOUNTER = 55;
    public static final int PONUMBER = 56;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwSrchResultVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Opn
     */
    public String getOpn() {
        return (String) getAttributeInternal(OPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Opn
     */
    public void setOpn(String value) {
        setAttributeInternal(OPN, value);
    }

    /**Gets the attribute value for the calculated attribute OrderNumber
     */
    public Number getOrderNumber() {
        return (Number) getAttributeInternal(ORDERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderNumber
     */
    public void setOrderNumber(Number value) {
        setAttributeInternal(ORDERNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute Rsd
     */
    public Date getRsd() {
        return (Date) getAttributeInternal(RSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Rsd
     */
    public void setRsd(Date value) {
        setAttributeInternal(RSD, value);
    }

    /**Gets the attribute value for the calculated attribute Ssd
     */
    public Date getSsd() {
        return (Date) getAttributeInternal(SSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Ssd
     */
    public void setSsd(Date value) {
        setAttributeInternal(SSD, value);
    }

    /**Gets the attribute value for the calculated attribute Quantity
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**Gets the attribute value for the calculated attribute HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**Gets the attribute value for the calculated attribute LineId
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**Gets the attribute value for the calculated attribute OrgId
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the attribute value for the calculated attribute LineNumber
     */
    public String getLineNumber() {
        return (String) getAttributeInternal(LINENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LineNumber
     */
    public void setLineNumber(String value) {
        setAttributeInternal(LINENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute ChangeType
     */
    public String getChangeType() {
        return (String) getAttributeInternal(CHANGETYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ChangeType
     */
    public void setChangeType(String value) {
        setAttributeInternal(CHANGETYPE, value);
    }

    /**Gets the attribute value for the calculated attribute NewRsd
     */
    public Date getNewRsd() {
        return (Date) getAttributeInternal(NEWRSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NewRsd
     */
    public void setNewRsd(Date value) {
        setAttributeInternal(NEWRSD, value);
    }

    /**Gets the attribute value for the calculated attribute NewQuantity
     */
    public Number getNewQuantity() {
        return (Number) getAttributeInternal(NEWQUANTITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NewQuantity
     */
    public void setNewQuantity(Number value) {
        setAttributeInternal(NEWQUANTITY, value);
    }

    /**Gets the attribute value for the calculated attribute Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for the calculated attribute CustCode
     */
    public String getCustCode() {
        return (String) getAttributeInternal(CUSTCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustCode
     */
    public void setCustCode(String value) {
        setAttributeInternal(CUSTCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Cust5Code
     */
    public String getCust5Code() {
        return (String) getAttributeInternal(CUST5CODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cust5Code
     */
    public void setCust5Code(String value) {
        setAttributeInternal(CUST5CODE, value);
    }

    /**Gets the attribute value for the calculated attribute OrderType
     */
    public String getOrderType() {
        return (String) getAttributeInternal(ORDERTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderType
     */
    public void setOrderType(String value) {
        setAttributeInternal(ORDERTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute OrderHold
     */
    public String getOrderHold() {
        return (String) getAttributeInternal(ORDERHOLD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderHold
     */
    public void setOrderHold(String value) {
        setAttributeInternal(ORDERHOLD, value);
    }

    /**Gets the attribute value for the calculated attribute LeadTime
     */
    public Number getLeadTime() {
        return (Number) getAttributeInternal(LEADTIME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LeadTime
     */
    public void setLeadTime(Number value) {
        setAttributeInternal(LEADTIME, value);
    }

    /**Gets the attribute value for the calculated attribute Mpq
     */
    public Number getMpq() {
        return (Number) getAttributeInternal(MPQ);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Mpq
     */
    public void setMpq(Number value) {
        setAttributeInternal(MPQ, value);
    }

    /**Gets the attribute value for the calculated attribute Pal
     */
    public String getPal() {
        return (String) getAttributeInternal(PAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pal
     */
    public void setPal(String value) {
        setAttributeInternal(PAL, value);
    }

    /**Gets the attribute value for the calculated attribute Package1
     */
    public String getPackage1() {
        return (String) getAttributeInternal(PACKAGE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Package1
     */
    public void setPackage1(String value) {
        setAttributeInternal(PACKAGE1, value);
    }

    /**Gets the attribute value for the calculated attribute ProdCategory
     */
    public String getProdCategory() {
        return (String) getAttributeInternal(PRODCATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProdCategory
     */
    public void setProdCategory(String value) {
        setAttributeInternal(PRODCATEGORY, value);
    }

    /**Gets the attribute value for the calculated attribute MaxqtyLeadTime
     */
    public Number getMaxqtyLeadTime() {
        return (Number) getAttributeInternal(MAXQTYLEADTIME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MaxqtyLeadTime
     */
    public void setMaxqtyLeadTime(Number value) {
        setAttributeInternal(MAXQTYLEADTIME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case OPN:
            return getOpn();
        case ORDERNUMBER:
            return getOrderNumber();
        case RSD:
            return getRsd();
        case SSD:
            return getSsd();
        case SAD:
            return getSad();
        case PLRSD:
            return getPlRsd();
        case PLNEWRSD:
            return getPlNewrsd();
        case QUANTITY:
            return getQuantity();
        case HEADERID:
            return getHeaderId();
        case LINEID:
            return getLineId();
        case ORGID:
            return getOrgId();
        case LINENUMBER:
            return getLineNumber();
        case CHANGETYPE:
            return getChangeType();
        case NEWRSD:
            return getNewRsd();
        case NEWSSD:
            return getNewSsd();
        case NEWQUANTITY:
            return getNewQuantity();
        case STATUS:
            return getStatus();
        case CUSTCODE:
            return getCustCode();
        case CUST5CODE:
            return getCust5Code();
        case ORDERTYPE:
            return getOrderType();
        case ORDERHOLD:
            return getOrderHold();
        case LEADTIME:
            return getLeadTime();
        case MPQ:
            return getMpq();
        case PAL:
            return getPal();
        case PACKAGE1:
            return getPackage1();
        case PRODCATEGORY:
            return getProdCategory();
        case MAXQTYLEADTIME:
            return getMaxqtyLeadTime();
        case STGLINEID:
            return getStgLineId();
        case STGHEADERID:
            return getStgHeaderId();
        case DBNQTY:
            return getDbNqty();
        case DBNRSD:
            return getDbNrsd();
        case DBPLRSD:
            return getDbPlrsd();
        case DBPLNEWRSD:
            return getDbPlnewrsd();
        case INVENTORYITEMID:
            return getInventoryItemId();
        case ORGANIZATIONID:
            return getOrganizationId();
        case ITEMNUMBER:
            return getItemNumber();
        case BIZCLASS:
            return getBizClass();
        case OPERUNIT:
            return getOperUnit();
        case ITEMSTATUS:
            return getItemStatus();
        case CUSTPONUMBER:
            return getCustPoNumber();
        case CUSTPOLINENUMBER:
            return getCustPoLineNumber();
        case PRICELIST:
            return getPriceList();
        case PRICELISTSTATUS:
            return getPriceListStatus();
        case CANCELREASON:
            return getCancelReason();
        case ISSELECT:
            return getisSelect();
        case DEMANDTYPE:
            return getdemandType();
        case ISREADONLY:
            return getisReadOnly();
        case DB_NEWSSD:
            return getdb_newSsd();
        case SSDREADONLY:
            return getssdReadOnly();
        case REASONCODE:
            return getreasonCode();
        case REASCODEREADONLY:
            return getreasCodeReadOnly();
        case PLANNERID:
            return getPlannerId();
        case SITEUSECODE:
            return getSiteUseCode();
        case LEGACYORDER:
            return getLegacyOrder();
        case LEGACYLINENUMBER:
            return getLegacyLineNumber();
        case SSDRESCEDULECOUNTER:
            return getSsdResceduleCounter();
        case PONUMBER:
            return getPoNumber();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case OPN:
            setOpn((String)value);
            return;
        case ORDERNUMBER:
            setOrderNumber((Number)value);
            return;
        case RSD:
            setRsd((Date)value);
            return;
        case SSD:
            setSsd((Date)value);
            return;
        case SAD:
            setSad((Date)value);
            return;
        case PLRSD:
            setPlRsd((Date)value);
            return;
        case PLNEWRSD:
            setPlNewrsd((Date)value);
            return;
        case QUANTITY:
            setQuantity((Number)value);
            return;
        case HEADERID:
            setHeaderId((Number)value);
            return;
        case LINEID:
            setLineId((Number)value);
            return;
        case ORGID:
            setOrgId((Number)value);
            return;
        case LINENUMBER:
            setLineNumber((String)value);
            return;
        case CHANGETYPE:
            setChangeType((String)value);
            return;
        case NEWRSD:
            setNewRsd((Date)value);
            return;
        case NEWSSD:
            setNewSsd((Date)value);
            return;
        case NEWQUANTITY:
            setNewQuantity((Number)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case CUSTCODE:
            setCustCode((String)value);
            return;
        case CUST5CODE:
            setCust5Code((String)value);
            return;
        case ORDERTYPE:
            setOrderType((String)value);
            return;
        case ORDERHOLD:
            setOrderHold((String)value);
            return;
        case LEADTIME:
            setLeadTime((Number)value);
            return;
        case MPQ:
            setMpq((Number)value);
            return;
        case PAL:
            setPal((String)value);
            return;
        case PACKAGE1:
            setPackage1((String)value);
            return;
        case PRODCATEGORY:
            setProdCategory((String)value);
            return;
        case MAXQTYLEADTIME:
            setMaxqtyLeadTime((Number)value);
            return;
        case STGLINEID:
            setStgLineId((Number)value);
            return;
        case STGHEADERID:
            setStgHeaderId((Number)value);
            return;
        case DBNQTY:
            setDbNqty((Number)value);
            return;
        case DBNRSD:
            setDbNrsd((Date)value);
            return;
        case DBPLRSD:
            setDbPlrsd((Date)value);
            return;
        case DBPLNEWRSD:
            setDbPlnewrsd((Date)value);
            return;
        case INVENTORYITEMID:
            setInventoryItemId((Number)value);
            return;
        case ORGANIZATIONID:
            setOrganizationId((Number)value);
            return;
        case ITEMNUMBER:
            setItemNumber((String)value);
            return;
        case BIZCLASS:
            setBizClass((String)value);
            return;
        case OPERUNIT:
            setOperUnit((String)value);
            return;
        case ITEMSTATUS:
            setItemStatus((String)value);
            return;
        case CUSTPONUMBER:
            setCustPoNumber((String)value);
            return;
        case CUSTPOLINENUMBER:
            setCustPoLineNumber((String)value);
            return;
        case PRICELIST:
            setPriceList((String)value);
            return;
        case PRICELISTSTATUS:
            setPriceListStatus((String)value);
            return;
        case CANCELREASON:
            setCancelReason((String)value);
            return;
        case ISSELECT:
            setisSelect((String)value);
            return;
        case DEMANDTYPE:
            setdemandType((String)value);
            return;
        case ISREADONLY:
            setisReadOnly((Boolean)value);
            return;
        case DB_NEWSSD:
            setdb_newSsd((String)value);
            return;
        case SSDREADONLY:
            setssdReadOnly((Boolean)value);
            return;
        case REASONCODE:
            setreasonCode((String)value);
            return;
        case REASCODEREADONLY:
            setreasCodeReadOnly((Boolean)value);
            return;
        case PLANNERID:
            setPlannerId((String)value);
            return;
        case SITEUSECODE:
            setSiteUseCode((String)value);
            return;
        case LEGACYORDER:
            setLegacyOrder((String)value);
            return;
        case LEGACYLINENUMBER:
            setLegacyLineNumber((String)value);
            return;
        case SSDRESCEDULECOUNTER:
            setSsdResceduleCounter((Number)value);
            return;
        case PONUMBER:
            setPoNumber((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute isSelect
     */
    public String getisSelect() {
        return (String) getAttributeInternal(ISSELECT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute isSelect
     */
    public void setisSelect(String value) {
        setAttributeInternal(ISSELECT, value);
    }

    /**Gets the attribute value for the calculated attribute demandType
     */
    public String getdemandType() {
        return (String) getAttributeInternal(DEMANDTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute demandType
     */
    public void setdemandType(String value) {
        setAttributeInternal(DEMANDTYPE, value);
    }


    /**Gets the attribute value for the calculated attribute StgLineId
     */
    public Number getStgLineId() {
        return (Number) getAttributeInternal(STGLINEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StgLineId
     */
    public void setStgLineId(Number value) {
        setAttributeInternal(STGLINEID, value);
    }


    /**Gets the attribute value for the calculated attribute DbNqty
     */
    public Number getDbNqty() {
        return (Number) getAttributeInternal(DBNQTY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DbNqty
     */
    public void setDbNqty(Number value) {
        setAttributeInternal(DBNQTY, value);
    }

    /**Gets the attribute value for the calculated attribute DbNrsd
     */
    public Date getDbNrsd() {
        return (Date) getAttributeInternal(DBNRSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DbNrsd
     */
    public void setDbNrsd(Date value) {
        setAttributeInternal(DBNRSD, value);
    }

    /**Gets the attribute value for the calculated attribute StgHeaderId
     */
    public Number getStgHeaderId() {
        return (Number) getAttributeInternal(STGHEADERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StgHeaderId
     */
    public void setStgHeaderId(Number value) {
        setAttributeInternal(STGHEADERID, value);
    }


    /**Gets the attribute value for the calculated attribute isReadOnly
     */
    public Boolean getisReadOnly() {
        return (Boolean) getAttributeInternal(ISREADONLY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute isReadOnly
     */
    public void setisReadOnly(Boolean value) {
        setAttributeInternal(ISREADONLY, value);
    }

    /**Gets the attribute value for the calculated attribute Sad
     */
    public Date getSad() {
        return (Date) getAttributeInternal(SAD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sad
     */
    public void setSad(Date value) {
        setAttributeInternal(SAD, value);
    }

    /**Gets the attribute value for the calculated attribute newSSD
     */
    public Date getnewSSD() {
        return (Date) getAttributeInternal(NEWSSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute newSSD
     */
    public void setnewSSD(Date value) {
        setAttributeInternal(NEWSSD, value);
    }

    /**Gets the attribute value for the calculated attribute PlRsd
     */
    public Date getPlRsd() {
        return (Date) getAttributeInternal(PLRSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PlRsd
     */
    public void setPlRsd(Date value) {
        setAttributeInternal(PLRSD, value);
    }

    /**Gets the attribute value for the calculated attribute PlNewrsd
     */
    public Date getPlNewrsd() {
        return (Date) getAttributeInternal(PLNEWRSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PlNewrsd
     */
    public void setPlNewrsd(Date value) {
        setAttributeInternal(PLNEWRSD, value);
    }

    /**Gets the attribute value for the calculated attribute DbPlrsd
     */
    public Date getDbPlrsd() {
        return (Date) getAttributeInternal(DBPLRSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DbPlrsd
     */
    public void setDbPlrsd(Date value) {
        setAttributeInternal(DBPLRSD, value);
    }

    /**Gets the attribute value for the calculated attribute DbPlnewrsd
     */
    public Date getDbPlnewrsd() {
        return (Date) getAttributeInternal(DBPLNEWRSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DbPlnewrsd
     */
    public void setDbPlnewrsd(Date value) {
        setAttributeInternal(DBPLNEWRSD, value);
    }

    /**Gets the attribute value for the calculated attribute db_newSsd
     */
    public String getdb_newSsd() {
        return (String) getAttributeInternal(DB_NEWSSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute db_newSsd
     */
    public void setdb_newSsd(String value) {
        setAttributeInternal(DB_NEWSSD, value);
    }

    /**Gets the attribute value for the calculated attribute NewSsd
     */
    public Date getNewSsd() {
        return (Date) getAttributeInternal(NEWSSD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NewSsd
     */
    public void setNewSsd(Date value) {
        setAttributeInternal(NEWSSD, value);
    }


    /**Gets the attribute value for the calculated attribute InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number) getAttributeInternal(INVENTORYITEMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**Gets the attribute value for the calculated attribute OrganizationId
     */
    public Number getOrganizationId() {
        return (Number) getAttributeInternal(ORGANIZATIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrganizationId
     */
    public void setOrganizationId(Number value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**Gets the attribute value for the calculated attribute ItemNumber
     */
    public String getItemNumber() {
        return (String) getAttributeInternal(ITEMNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemNumber
     */
    public void setItemNumber(String value) {
        setAttributeInternal(ITEMNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute BizClass
     */
    public String getBizClass() {
        return (String) getAttributeInternal(BIZCLASS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BizClass
     */
    public void setBizClass(String value) {
        setAttributeInternal(BIZCLASS, value);
    }

    /**Gets the attribute value for the calculated attribute OperUnit
     */
    public String getOperUnit() {
        return (String) getAttributeInternal(OPERUNIT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OperUnit
     */
    public void setOperUnit(String value) {
        setAttributeInternal(OPERUNIT, value);
    }

    /**Gets the attribute value for the calculated attribute ItemStatus
     */
    public String getItemStatus() {
        return (String) getAttributeInternal(ITEMSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemStatus
     */
    public void setItemStatus(String value) {
        setAttributeInternal(ITEMSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute CustPoNumber
     */
    public String getCustPoNumber() {
        return (String) getAttributeInternal(CUSTPONUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustPoNumber
     */
    public void setCustPoNumber(String value) {
        setAttributeInternal(CUSTPONUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute CustPoLineNumber
     */
    public String getCustPoLineNumber() {
        return (String) getAttributeInternal(CUSTPOLINENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustPoLineNumber
     */
    public void setCustPoLineNumber(String value) {
        setAttributeInternal(CUSTPOLINENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute PriceList
     */
    public String getPriceList() {
        return (String) getAttributeInternal(PRICELIST);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PriceList
     */
    public void setPriceList(String value) {
        setAttributeInternal(PRICELIST, value);
    }

    /**Gets the attribute value for the calculated attribute PriceListStatus
     */
    public String getPriceListStatus() {
        return (String) getAttributeInternal(PRICELISTSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PriceListStatus
     */
    public void setPriceListStatus(String value) {
        setAttributeInternal(PRICELISTSTATUS, value);
    }


    /**Gets the attribute value for the calculated attribute ssdReadOnly
     */
    public Boolean getssdReadOnly() {
        return (Boolean) getAttributeInternal(SSDREADONLY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ssdReadOnly
     */
    public void setssdReadOnly(Boolean value) {
        setAttributeInternal(SSDREADONLY, value);
    }

    /**Gets the attribute value for the calculated attribute reasonCode
     */
    public String getreasonCode() {
        return (String) getAttributeInternal(REASONCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute reasonCode
     */
    public void setreasonCode(String value) {
        setAttributeInternal(REASONCODE, value);
    }

    /**Gets the attribute value for the calculated attribute CancelReason
     */
    public String getCancelReason() {
        return (String) getAttributeInternal(CANCELREASON);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CancelReason
     */
    public void setCancelReason(String value) {
        setAttributeInternal(CANCELREASON, value);
    }

    /**Gets the attribute value for the calculated attribute reasCodeReadOnly
     */
    public Boolean getreasCodeReadOnly() {
        return (Boolean) getAttributeInternal(REASCODEREADONLY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute reasCodeReadOnly
     */
    public void setreasCodeReadOnly(Boolean value) {
        setAttributeInternal(REASCODEREADONLY, value);
    }

    /**Gets the attribute value for the calculated attribute PlannerId
     */
    public String getPlannerId() {
        return (String) getAttributeInternal(PLANNERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PlannerId
     */
    public void setPlannerId(String value) {
        setAttributeInternal(PLANNERID, value);
    }

    /**Gets the attribute value for the calculated attribute SiteUseCode
     */
    public String getSiteUseCode() {
        return (String) getAttributeInternal(SITEUSECODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SiteUseCode
     */
    public void setSiteUseCode(String value) {
        setAttributeInternal(SITEUSECODE, value);
    }

    /**Gets the attribute value for the calculated attribute LegacyOrder
     */
    public String getLegacyOrder() {
        return (String) getAttributeInternal(LEGACYORDER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LegacyOrder
     */
    public void setLegacyOrder(String value) {
        setAttributeInternal(LEGACYORDER, value);
    }

    /**Gets the attribute value for the calculated attribute LegacyLineNumber
     */
    public String getLegacyLineNumber() {
        return (String) getAttributeInternal(LEGACYLINENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LegacyLineNumber
     */
    public void setLegacyLineNumber(String value) {
        setAttributeInternal(LEGACYLINENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute SsdResceduleCounter
     */
    public Number getSsdResceduleCounter() {
        return (Number) getAttributeInternal(SSDRESCEDULECOUNTER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SsdResceduleCounter
     */
    public void setSsdResceduleCounter(Number value) {
        setAttributeInternal(SSDRESCEDULECOUNTER, value);
    }

    /**Gets the attribute value for the calculated attribute PoNumber
     */
    public String getPoNumber() {
        return (String) getAttributeInternal(PONUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoNumber
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }
}
