package oracle.apps.xxon.om.gbw.audit.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXOnGbwAuditRecordDisplayVORowImpl extends OAViewRowImpl {

    public static final int DUMMY = 0;
    public static final int ROWSTOBEDISPLAYED = 1;
    public static final int RECCOUNT = 2;

    /**This is the default constructor (do not remove)
     */
    public XXOnGbwAuditRecordDisplayVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Dummy
     */
    public void setDummy(String value) {
        setAttributeInternal(DUMMY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            return getDummy();
        case ROWSTOBEDISPLAYED:
            return getrowsToBeDisplayed();
        case RECCOUNT:
            return getrecCount();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            setDummy((String)value);
            return;
        case ROWSTOBEDISPLAYED:
            setrowsToBeDisplayed((String)value);
            return;
        case RECCOUNT:
            setrecCount((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the attribute value for the calculated attribute rowsToBeDisplayed
     */
    public String getrowsToBeDisplayed() {
        return (String) getAttributeInternal(ROWSTOBEDISPLAYED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute rowsToBeDisplayed
     */
    public void setrowsToBeDisplayed(String value) {
        setAttributeInternal(ROWSTOBEDISPLAYED, value);
    }


    /**Gets the attribute value for the calculated attribute recCount
     */
    public String getrecCount() {
        return (String) getAttributeInternal(RECCOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute recCount
     */
    public void setrecCount(String value) {
        setAttributeInternal(RECCOUNT, value);
    }
}
