package oracle.apps.xxon.om.gbw.audit.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwSearchValuesVORowImpl extends OAViewRowImpl {

    public static final int DUMMY = 0;
    public static final int OPN = 1;
    public static final int CORPCODE = 2;
    public static final int PKGCODE = 3;
    public static final int OU = 4;
    public static final int CUST5CODE = 5;
    public static final int PAL = 6;
    public static final int ORDERNUMBER = 7;
    public static final int ORDERTYPE = 8;
    public static final int HISTORYFROMDATE = 9;
    public static final int HISTORYTODATE = 10;
    public static final int DATERANGE = 11;
    public static final int DEMANDTYPE = 12;
    public static final int LEGACYORDERNUMBER = 13;
    public static final int USERNAME = 14;
    public static final int ORDEROPN = 15;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwSearchValuesVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Dummy
     */
    public void setDummy(String value) {
        setAttributeInternal(DUMMY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            return getDummy();
        case OPN:
            return getOpn();
        case CORPCODE:
            return getCorpCode();
        case PKGCODE:
            return getPkgCode();
        case OU:
            return getOu();
        case CUST5CODE:
            return getCust5Code();
        case PAL:
            return getPal();
        case ORDERNUMBER:
            return getorderNumber();
        case ORDERTYPE:
            return getorderType();
        case HISTORYFROMDATE:
            return gethistoryFromDate();
        case HISTORYTODATE:
            return gethistoryToDate();
        case DATERANGE:
            return getDateRange();
        case DEMANDTYPE:
            return getDemandType();
        case LEGACYORDERNUMBER:
            return getLegacyOrderNumber();
        case USERNAME:
            return getUserName();
        case ORDEROPN:
            return getOrderOpn();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            setDummy((String)value);
            return;
        case OPN:
            setOpn((String)value);
            return;
        case CORPCODE:
            setCorpCode((String)value);
            return;
        case PKGCODE:
            setPkgCode((String)value);
            return;
        case OU:
            setOu((String)value);
            return;
        case CUST5CODE:
            setCust5Code((String)value);
            return;
        case PAL:
            setPal((String)value);
            return;
        case ORDERNUMBER:
            setorderNumber((String)value);
            return;
        case ORDERTYPE:
            setorderType((String)value);
            return;
        case HISTORYFROMDATE:
            sethistoryFromDate((Date)value);
            return;
        case HISTORYTODATE:
            sethistoryToDate((Date)value);
            return;
        case DATERANGE:
            setDateRange((String)value);
            return;
        case DEMANDTYPE:
            setDemandType((String)value);
            return;
        case LEGACYORDERNUMBER:
            setLegacyOrderNumber((String)value);
            return;
        case USERNAME:
            setUserName((String)value);
            return;
        case ORDEROPN:
            setOrderOpn((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Opn
     */
    public String getOpn() {
        return (String) getAttributeInternal(OPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Opn
     */
    public void setOpn(String value) {
        setAttributeInternal(OPN, value);
    }

    /**Gets the attribute value for the calculated attribute CorpCode
     */
    public String getCorpCode() {
        return (String) getAttributeInternal(CORPCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CorpCode
     */
    public void setCorpCode(String value) {
        setAttributeInternal(CORPCODE, value);
    }

    /**Gets the attribute value for the calculated attribute PkgCode
     */
    public String getPkgCode() {
        return (String) getAttributeInternal(PKGCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PkgCode
     */
    public void setPkgCode(String value) {
        setAttributeInternal(PKGCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Ou
     */
    public String getOu() {
        return (String) getAttributeInternal(OU);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Ou
     */
    public void setOu(String value) {
        setAttributeInternal(OU, value);
    }

    /**Gets the attribute value for the calculated attribute Cust5Code
     */
    public String getCust5Code() {
        return (String) getAttributeInternal(CUST5CODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cust5Code
     */
    public void setCust5Code(String value) {
        setAttributeInternal(CUST5CODE, value);
    }

    /**Gets the attribute value for the calculated attribute Pal
     */
    public String getPal() {
        return (String) getAttributeInternal(PAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pal
     */
    public void setPal(String value) {
        setAttributeInternal(PAL, value);
    }

    /**Gets the attribute value for the calculated attribute orderNumber
     */
    public String getorderNumber() {
        return (String) getAttributeInternal(ORDERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute orderNumber
     */
    public void setorderNumber(String value) {
        setAttributeInternal(ORDERNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute orderType
     */
    public String getorderType() {
        return (String) getAttributeInternal(ORDERTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute orderType
     */
    public void setorderType(String value) {
        setAttributeInternal(ORDERTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute historyFromDate
     */
    public Date gethistoryFromDate() {
        return (Date) getAttributeInternal(HISTORYFROMDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute historyFromDate
     */
    public void sethistoryFromDate(Date value) {
        setAttributeInternal(HISTORYFROMDATE, value);
    }

    /**Gets the attribute value for the calculated attribute historyToDate
     */
    public Date gethistoryToDate() {
        return (Date) getAttributeInternal(HISTORYTODATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute historyToDate
     */
    public void sethistoryToDate(Date value) {
        setAttributeInternal(HISTORYTODATE, value);
    }

    /**Gets the attribute value for the calculated attribute DateRange
     */
    public String getDateRange() {
        return (String) getAttributeInternal(DATERANGE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DateRange
     */
    public void setDateRange(String value) {
        setAttributeInternal(DATERANGE, value);
    }

    /**Gets the attribute value for the calculated attribute DemandType
     */
    public String getDemandType() {
        return (String) getAttributeInternal(DEMANDTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DemandType
     */
    public void setDemandType(String value) {
        setAttributeInternal(DEMANDTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute LegacyOrderNumber
     */
    public String getLegacyOrderNumber() {
        return (String) getAttributeInternal(LEGACYORDERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LegacyOrderNumber
     */
    public void setLegacyOrderNumber(String value) {
        setAttributeInternal(LEGACYORDERNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute UserName
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UserName
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute OrderOpn
     */
    public String getOrderOpn() {
        return (String) getAttributeInternal(ORDEROPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderOpn
     */
    public void setOrderOpn(String value) {
        setAttributeInternal(ORDEROPN, value);
    }
}
