package oracle.apps.xxon.om.gbw.audit.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwAuditResultVORowImpl extends OAViewRowImpl {
    public static final int AUDITUSERNAME = 0;
    public static final int AUDITTIMESTAMP = 1;
    public static final int ORDERNUMBER = 2;
    public static final int ATTRIBUTENAME = 3;
    public static final int NEWATTRIBUTEVALUE = 4;
    public static final int OLDATTRIBUTEVALUE = 5;
    public static final int LINENUMBER = 6;
    public static final int AUDITLEVEL = 7;
    public static final int RESPONSIBILITYNAME = 8;
    public static final int HEADERID = 9;
    public static final int ITEMNAME = 10;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwAuditResultVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute AuditUserName
     */
    public String getAuditUserName() {
        return (String) getAttributeInternal(AUDITUSERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AuditUserName
     */
    public void setAuditUserName(String value) {
        setAttributeInternal(AUDITUSERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute AuditTimestamp
     */
    public Date getAuditTimestamp() {
        return (Date) getAttributeInternal(AUDITTIMESTAMP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AuditTimestamp
     */
    public void setAuditTimestamp(Date value) {
        setAttributeInternal(AUDITTIMESTAMP, value);
    }

    /**Gets the attribute value for the calculated attribute OrderNumber
     */
    public String getOrderNumber() {
        return (String) getAttributeInternal(ORDERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderNumber
     */
    public void setOrderNumber(String value) {
        setAttributeInternal(ORDERNUMBER, value);
    }


    /**Gets the attribute value for the calculated attribute AttributeName
     */
    public String getAttributeName() {
        return (String) getAttributeInternal(ATTRIBUTENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AttributeName
     */
    public void setAttributeName(String value) {
        setAttributeInternal(ATTRIBUTENAME, value);
    }

    /**Gets the attribute value for the calculated attribute NewAttributeValue
     */
    public String getNewAttributeValue() {
        return (String) getAttributeInternal(NEWATTRIBUTEVALUE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NewAttributeValue
     */
    public void setNewAttributeValue(String value) {
        setAttributeInternal(NEWATTRIBUTEVALUE, value);
    }

    /**Gets the attribute value for the calculated attribute OldAttributeValue
     */
    public String getOldAttributeValue() {
        return (String) getAttributeInternal(OLDATTRIBUTEVALUE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OldAttributeValue
     */
    public void setOldAttributeValue(String value) {
        setAttributeInternal(OLDATTRIBUTEVALUE, value);
    }


    /**Gets the attribute value for the calculated attribute LineNumber
     */
    public String getLineNumber() {
        return (String) getAttributeInternal(LINENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LineNumber
     */
    public void setLineNumber(String value) {
        setAttributeInternal(LINENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute AuditLevel
     */
    public String getAuditLevel() {
        return (String) getAttributeInternal(AUDITLEVEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AuditLevel
     */
    public void setAuditLevel(String value) {
        setAttributeInternal(AUDITLEVEL, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case AUDITUSERNAME:
            return getAuditUserName();
        case AUDITTIMESTAMP:
            return getAuditTimestamp();
        case ORDERNUMBER:
            return getOrderNumber();
        case ATTRIBUTENAME:
            return getAttributeName();
        case NEWATTRIBUTEVALUE:
            return getNewAttributeValue();
        case OLDATTRIBUTEVALUE:
            return getOldAttributeValue();
        case LINENUMBER:
            return getLineNumber();
        case AUDITLEVEL:
            return getAuditLevel();
        case RESPONSIBILITYNAME:
            return getResponsibilityName();
        case HEADERID:
            return getHeaderId();
        case ITEMNAME:
            return getItemName();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case AUDITUSERNAME:
            setAuditUserName((String)value);
            return;
        case AUDITTIMESTAMP:
            setAuditTimestamp((Date)value);
            return;
        case ORDERNUMBER:
            setOrderNumber((String)value);
            return;
        case ATTRIBUTENAME:
            setAttributeName((String)value);
            return;
        case NEWATTRIBUTEVALUE:
            setNewAttributeValue((String)value);
            return;
        case OLDATTRIBUTEVALUE:
            setOldAttributeValue((String)value);
            return;
        case LINENUMBER:
            setLineNumber((String)value);
            return;
        case AUDITLEVEL:
            setAuditLevel((String)value);
            return;
        case RESPONSIBILITYNAME:
            setResponsibilityName((String)value);
            return;
        case HEADERID:
            setHeaderId((Number)value);
            return;
        case ITEMNAME:
            setItemName((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the attribute value for the calculated attribute ResponsibilityName
     */
    public String getResponsibilityName() {
        return (String) getAttributeInternal(RESPONSIBILITYNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ResponsibilityName
     */
    public void setResponsibilityName(String value) {
        setAttributeInternal(RESPONSIBILITYNAME, value);
    }

    /**Gets the attribute value for the calculated attribute HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**Gets the attribute value for the calculated attribute ItemName
     */
    public String getItemName() {
        return (String) getAttributeInternal(ITEMNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemName
     */
    public void setItemName(String value) {
        setAttributeInternal(ITEMNAME, value);
    }
}
