package oracle.apps.xxon.om.gbw.audit.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwAuditHeaderVORowImpl extends OAViewRowImpl {
    public static final int ORDERNUMBER = 0;
    public static final int HEADERID = 1;
    public static final int CORPCODE = 2;
    public static final int CUST5CODE = 3;
    public static final int PAL = 4;
    public static final int PACKAGECD = 5;
    public static final int AUDITLEVEL = 6;
    public static final int RADIOBTNVAL = 7;
    public static final int ORDLINENUMBER = 8;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwAuditHeaderVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute OrderNumber
     */
    public String getOrderNumber() {
        return (String) getAttributeInternal(ORDERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderNumber
     */
    public void setOrderNumber(String value) {
        setAttributeInternal(ORDERNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**Gets the attribute value for the calculated attribute CorpCode
     */
    public String getCorpCode() {
        return (String) getAttributeInternal(CORPCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CorpCode
     */
    public void setCorpCode(String value) {
        setAttributeInternal(CORPCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Cust5Code
     */
    public String getCust5Code() {
        return (String) getAttributeInternal(CUST5CODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cust5Code
     */
    public void setCust5Code(String value) {
        setAttributeInternal(CUST5CODE, value);
    }

    /**Gets the attribute value for the calculated attribute Pal
     */
    public String getPal() {
        return (String) getAttributeInternal(PAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pal
     */
    public void setPal(String value) {
        setAttributeInternal(PAL, value);
    }

    /**Gets the attribute value for the calculated attribute PackageCd
     */
    public String getPackageCd() {
        return (String) getAttributeInternal(PACKAGECD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PackageCd
     */
    public void setPackageCd(String value) {
        setAttributeInternal(PACKAGECD, value);
    }

    /**Gets the attribute value for the calculated attribute AuditLevel
     */
    public String getAuditLevel() {
        return (String) getAttributeInternal(AUDITLEVEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AuditLevel
     */
    public void setAuditLevel(String value) {
        setAttributeInternal(AUDITLEVEL, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ORDERNUMBER:
            return getOrderNumber();
        case HEADERID:
            return getHeaderId();
        case CORPCODE:
            return getCorpCode();
        case CUST5CODE:
            return getCust5Code();
        case PAL:
            return getPal();
        case PACKAGECD:
            return getPackageCd();
        case AUDITLEVEL:
            return getAuditLevel();
        case RADIOBTNVAL:
            return getRadioBtnVal();
        case ORDLINENUMBER:
            return getOrdLineNumber();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ORDERNUMBER:
            setOrderNumber((String)value);
            return;
        case HEADERID:
            setHeaderId((Number)value);
            return;
        case CORPCODE:
            setCorpCode((String)value);
            return;
        case CUST5CODE:
            setCust5Code((String)value);
            return;
        case PAL:
            setPal((String)value);
            return;
        case PACKAGECD:
            setPackageCd((String)value);
            return;
        case AUDITLEVEL:
            setAuditLevel((String)value);
            return;
        case RADIOBTNVAL:
            setRadioBtnVal((String)value);
            return;
        case ORDLINENUMBER:
            setOrdLineNumber((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute radioBtnVal
     */
    public String getradioBtnVal() {
        return (String) getAttributeInternal(RADIOBTNVAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute radioBtnVal
     */
    public void setradioBtnVal(String value) {
        setAttributeInternal(RADIOBTNVAL, value);
    }


    /**Gets the attribute value for the calculated attribute OrdLineNumber
     */
    public String getOrdLineNumber() {
        return (String) getAttributeInternal(ORDLINENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrdLineNumber
     */
    public void setOrdLineNumber(String value) {
        setAttributeInternal(ORDLINENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute RadioBtnVal
     */
    public String getRadioBtnVal() {
        return (String) getAttributeInternal(RADIOBTNVAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RadioBtnVal
     */
    public void setRadioBtnVal(String value) {
        setAttributeInternal(RADIOBTNVAL, value);
    }
}
