package oracle.apps.xxon.om.gbw.schctl.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwScheCtlResultVORowImpl extends OAViewRowImpl {
    public static final int OPN = 0;
    public static final int PTI = 1;
    public static final int PKG = 2;
    public static final int OUNAME = 3;
    public static final int SCHEDULINGMETHOD = 4;
    public static final int LASTUPDATEDBY = 5;
    public static final int LASTUPDATEDATE = 6;
    public static final int SCHCTLLEVEL = 7;
    public static final int SCHCONTROLID = 8;
    public static final int INVENTORYITEMID = 9;
    public static final int NEWROW = 10;
    public static final int FLEXVALUESETNAME = 11;
    public static final int SELECT = 12;
    public static final int READONLYPTI = 13;
    public static final int READONLYOU = 14;
    public static final int ORGID = 15;
    public static final int INVENTORYITEMID1 = 16;
    public static final int READONLYMPN = 17;
    public static final int READONLYPKG = 18;
    public static final int PKGCODE = 19;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwScheCtlResultVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute SchedulingMethod
     */
    public String getSchedulingMethod() {
        return (String) getAttributeInternal(SCHEDULINGMETHOD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SchedulingMethod
     */
    public void setSchedulingMethod(String value) {
        setAttributeInternal(SCHEDULINGMETHOD, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute OuName
     */
    public String getOuName() {
        return (String) getAttributeInternal(OUNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OuName
     */
    public void setOuName(String value) {
        setAttributeInternal(OUNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Opn
     */
    public String getOpn() {
        return (String) getAttributeInternal(OPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Opn
     */
    public void setOpn(String value) {
        setAttributeInternal(OPN, value);
    }

    /**Gets the attribute value for the calculated attribute Pti
     */
    public String getPti() {
        return (String) getAttributeInternal(PTI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pti
     */
    public void setPti(String value) {
        setAttributeInternal(PTI, value);
    }

    /**Gets the attribute value for the calculated attribute Pkg
     */
    public String getPkg() {
        return (String) getAttributeInternal(PKG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pkg
     */
    public void setPkg(String value) {
        setAttributeInternal(PKG, value);
    }

    /**Gets the attribute value for the calculated attribute SchctlLevel
     */
    public String getSchctlLevel() {
        return (String) getAttributeInternal(SCHCTLLEVEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SchctlLevel
     */
    public void setSchctlLevel(String value) {
        setAttributeInternal(SCHCTLLEVEL, value);
    }

    /**Gets the attribute value for the calculated attribute SchControlId
     */
    public Number getSchControlId() {
        return (Number) getAttributeInternal(SCHCONTROLID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SchControlId
     */
    public void setSchControlId(Number value) {
        setAttributeInternal(SCHCONTROLID, value);
    }

    /**Gets the attribute value for the calculated attribute select
     */
    public String getselect() {
        return (String) getAttributeInternal(SELECT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute select
     */
    public void setselect(String value) {
        setAttributeInternal(SELECT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case OPN:
            return getOpn();
        case PTI:
            return getPti();
        case PKG:
            return getPkg();
        case OUNAME:
            return getOuName();
        case SCHEDULINGMETHOD:
            return getSchedulingMethod();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case SCHCTLLEVEL:
            return getSchctlLevel();
        case SCHCONTROLID:
            return getSchControlId();
        case INVENTORYITEMID:
            return getInventoryItemId();
        case NEWROW:
            return getNewRow();
        case FLEXVALUESETNAME:
            return getFlexValueSetName();
        case SELECT:
            return getselect();
        case READONLYPTI:
            return getReadOnlyPti();
        case READONLYOU:
            return getReadOnlyOu();
        case ORGID:
            return getOrgId();
        case INVENTORYITEMID1:
            return getInventoryItemId1();
        case READONLYMPN:
            return getReadOnlyMpn();
        case READONLYPKG:
            return getReadOnlyPkg();
        case PKGCODE:
            return getPkgCode();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case OPN:
            setOpn((String)value);
            return;
        case PTI:
            setPti((String)value);
            return;
        case PKG:
            setPkg((String)value);
            return;
        case OUNAME:
            setOuName((String)value);
            return;
        case SCHEDULINGMETHOD:
            setSchedulingMethod((String)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case SCHCTLLEVEL:
            setSchctlLevel((String)value);
            return;
        case SCHCONTROLID:
            setSchControlId((Number)value);
            return;
        case INVENTORYITEMID:
            setInventoryItemId((Number)value);
            return;
        case NEWROW:
            setNewRow((String)value);
            return;
        case FLEXVALUESETNAME:
            setFlexValueSetName((String)value);
            return;
        case SELECT:
            setselect((String)value);
            return;
        case READONLYPTI:
            setReadOnlyPti((Boolean)value);
            return;
        case READONLYOU:
            setReadOnlyOu((Boolean)value);
            return;
        case ORGID:
            setOrgId((String)value);
            return;
        case INVENTORYITEMID1:
            setInventoryItemId1((String)value);
            return;
        case READONLYMPN:
            setReadOnlyMpn((Boolean)value);
            return;
        case READONLYPKG:
            setReadOnlyPkg((Boolean)value);
            return;
        case PKGCODE:
            setPkgCode((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute NewRow
     */
    public String getNewRow() {
        return (String) getAttributeInternal(NEWROW);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NewRow
     */
    public void setNewRow(String value) {
        setAttributeInternal(NEWROW, value);
    }

    /**Gets the attribute value for the calculated attribute ReadOnlyPti
     */
    public Boolean getReadOnlyPti() 
    {
//      if(getNewRow()!=null&&getNewRow().equals("Y"))
//      {
//          return Boolean.FALSE;
//      }else{
//          return Boolean.TRUE;
//      }
       return (Boolean) getAttributeInternal(READONLYPTI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReadOnlyPti
     */
    public void setReadOnlyPti(Boolean value) {
        setAttributeInternal(READONLYPTI, value);
    }

    /**Gets the attribute value for the calculated attribute ReadOnlyOu
     */
    public Boolean getReadOnlyOu()
    {
//        if(getNewRow()!=null&&getNewRow().equals("Y"))
//        {
//            return Boolean.FALSE;
//        }else{
//            return Boolean.TRUE;
//        }
        return (Boolean) getAttributeInternal(READONLYOU);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReadOnlyOu
     */
    public void setReadOnlyOu(Boolean value) {
        setAttributeInternal(READONLYOU, value);
    }

    /**Gets the attribute value for the calculated attribute OrgId
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrgId
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the attribute value for the calculated attribute InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number) getAttributeInternal(INVENTORYITEMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**Gets the attribute value for the calculated attribute FlexValueSetName
     */
    public String getFlexValueSetName() {
        return (String) getAttributeInternal(FLEXVALUESETNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FlexValueSetName
     */
    public void setFlexValueSetName(String value) {
        setAttributeInternal(FLEXVALUESETNAME, value);
    }

    /**Gets the attribute value for the calculated attribute InventoryItemId1
     */
    public String getInventoryItemId1() {
        return (String) getAttributeInternal(INVENTORYITEMID1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InventoryItemId1
     */
    public void setInventoryItemId1(String value) {
        setAttributeInternal(INVENTORYITEMID1, value);
    }

    /**Gets the attribute value for the calculated attribute ReadOnlyMpn
     */
    public Boolean getReadOnlyMpn() 
    {
    
//        if(getNewRow()!=null&&getNewRow().equals("Y"))
//        {
//            return Boolean.FALSE;
//        }else{
//            return Boolean.TRUE;
//        }
        return (Boolean) getAttributeInternal(READONLYMPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReadOnlyMpn
     */
    public void setReadOnlyMpn(Boolean value) {
        setAttributeInternal(READONLYMPN, value);
    }

    /**Gets the attribute value for the calculated attribute ReadOnlyPkg
     */
    public Boolean getReadOnlyPkg() 
    {
//        if(getNewRow()!=null&&getNewRow().equals("Y"))
//        {
//            return Boolean.FALSE;
//        }else{
//            return Boolean.TRUE;
//        }
        return (Boolean) getAttributeInternal(READONLYPKG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReadOnlyPkg
     */
    public void setReadOnlyPkg(Boolean value) {
        setAttributeInternal(READONLYPKG, value);
    }

    /**Gets the attribute value for the calculated attribute PkgCode
     */
    public String getPkgCode() {
        return (String) getAttributeInternal(PKGCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PkgCode
     */
    public void setPkgCode(String value) {
        setAttributeInternal(PKGCODE, value);
    }


}
