package oracle.apps.xxon.om.gbw.schctl.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwScheDuplicateCheckVORowImpl extends OAViewRowImpl {
    public static final int COUNT1_1 = 0;
    public static final int RECCOUNT = 1;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwScheDuplicateCheckVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Count1_1
     */
    public Number getCount1_1() {
        return (Number) getAttributeInternal(COUNT1_1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Count1_1
     */
    public void setCount1_1(Number value) {
        setAttributeInternal(COUNT1_1, value);
    }

    /**Gets the attribute value for the calculated attribute RecCount
     */
    public Number getRecCount() {
        return (Number) getAttributeInternal(RECCOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RecCount
     */
    public void setRecCount(Number value) {
        setAttributeInternal(RECCOUNT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case COUNT1_1:
            return getCount1_1();
        case RECCOUNT:
            return getRecCount();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case COUNT1_1:
            setCount1_1((Number)value);
            return;
        case RECCOUNT:
            setRecCount((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
