package oracle.apps.xxon.om.gbw.schctl.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwSearchValuesVORowImpl extends OAViewRowImpl {
    public static final int DUMMY = 0;
    public static final int OPN = 1;
    public static final int PTI = 2;
    public static final int PKG = 3;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwSearchValuesVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Dummy
     */
    public void setDummy(String value) {
        setAttributeInternal(DUMMY, value);
    }

    /**Gets the attribute value for the calculated attribute Opn
     */
    public String getOpn() {
        return (String) getAttributeInternal(OPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Opn
     */
    public void setOpn(String value) {
        setAttributeInternal(OPN, value);
    }

    /**Gets the attribute value for the calculated attribute Pti
     */
    public String getPti() {
        return (String) getAttributeInternal(PTI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pti
     */
    public void setPti(String value) {
        setAttributeInternal(PTI, value);
    }

    /**Gets the attribute value for the calculated attribute Pkg
     */
    public String getPkg() {
        return (String) getAttributeInternal(PKG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pkg
     */
    public void setPkg(String value) {
        setAttributeInternal(PKG, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            return getDummy();
        case OPN:
            return getOpn();
        case PTI:
            return getPti();
        case PKG:
            return getPkg();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            setDummy((String)value);
            return;
        case OPN:
            setOpn((String)value);
            return;
        case PTI:
            setPti((String)value);
            return;
        case PKG:
            setPkg((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


}
