package oracle.apps.xxon.om.gbw.invres.server;

import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.xxon.om.gbw.baklogview.server.XXONGbwRecordsDisplayVOImpl;
import oracle.apps.xxon.om.gbw.baklogview.server.XXONGbwRecordsDisplayVORowImpl;
import oracle.apps.xxon.om.gbw.lov.server.XXONGbwCorpCodeLovVOImpl;
import oracle.apps.xxon.om.gbw.lov.server.XXONGbwCust5CodeLovVOImpl;
import oracle.apps.xxon.om.gbw.lov.server.XXONGbwPackageLovVOImpl;
import oracle.apps.xxon.om.gbw.lov.server.XXONGbwPtiLovVOImpl;
import oracle.apps.xxon.om.gbw.util.XXONGbwUtil;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwIrSearchAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public XXONGbwIrSearchAMImpl() {
    }
    XXONGbwUtil utils= new XXONGbwUtil();
    public void recDisInit()
    {
        XXONGbwRecordsDisplayVOImpl recordsDisplayVO=getXXONGbwRecordsDisplayVO1();
        if(!recordsDisplayVO.isExecuted())
        {
            recordsDisplayVO.executeQuery();
        }
    
    }
    public void initSearchValuesVO()
    {
        XXONGbwIrSerachValuesVOImpl vo=getXXONGbwIrSerachValuesVO1();
        if(!vo.isExecuted())
        {
            vo.executeQuery();
        }
    
    }
    public void exeResult()
    {
        XXONGbwIrSerachValuesVOImpl vo=getXXONGbwIrSerachValuesVO1();
        XXONGbwIrSerachValuesVORowImpl row=(XXONGbwIrSerachValuesVORowImpl)vo.first();
        String opn=null;
        String pal=null;
        String pkg=null;
        String corpCode=null;
        String cust5code=null;
        String source=null;
        opn=row.getOPN();
        pal=row.getpal();
        pkg=row.getpkg();
        corpCode=row.getCorpCode();
        cust5code=row.getCust5Code();
        source=row.getsourceItem();
        
        if(pal!=null&&pal.trim().length()>0&&pal.contains("%"))
        {
           throw new OAException("XXON","XXON_OM_GBW_BLV_SEARCH_ERR1",null,OAException.ERROR,null);
        }
        XXONGbwIrSearchVOImpl IrSearchVO=getXXONGbwIrSearchVO1();
        IrSearchVO.setWhereClauseParams(null);
        IrSearchVO.setWhereClause("1=1");
       
        int javaBindNum=0;
        if(opn!=null&&opn.trim().length()>0)
        {
         if(opn.contains("%"))
         {
            javaBindNum++;
            IrSearchVO.addWhereClause(" AND MPN LIKE :"+javaBindNum);
            IrSearchVO.setWhereClauseParam(javaBindNum-1,opn.toUpperCase());
         }else{
             javaBindNum++;
             IrSearchVO.addWhereClause(" AND MPN = :"+javaBindNum);
             IrSearchVO.setWhereClauseParam(javaBindNum-1,opn.toUpperCase());
         }
        }
        if(pal!=null&&pal.trim().length()>0)
        {
             if(pal.trim().length()>3)
             {
                 javaBindNum++;
                 IrSearchVO.addWhereClause(" AND PTI4 = :"+javaBindNum);
                 IrSearchVO.setWhereClauseParam(javaBindNum-1,pal.toUpperCase());
             }else if(pal.trim().length()==3)
             {
                     javaBindNum++;
                     IrSearchVO.addWhereClause(" AND SUBSTR(PTI4,0,3) = :"+javaBindNum);
                     IrSearchVO.setWhereClauseParam(javaBindNum-1,pal.toUpperCase());
             
             }else if(pal.trim().length()==2)
             {
                 javaBindNum++;
                 IrSearchVO.addWhereClause(" AND SUBSTR(PTI4,0,2) = :"+javaBindNum);
                 IrSearchVO.setWhereClauseParam(javaBindNum-1,pal.toUpperCase());
             }
        }
        if(pkg!=null&&pkg.trim().length()>0)
        {
          if(pkg.contains("%"))
          {
            javaBindNum++;
            IrSearchVO.addWhereClause(" AND PACKAGE_STD_CD LIKE :"+javaBindNum);
            IrSearchVO.setWhereClauseParam(javaBindNum-1,pkg.toUpperCase());
          }else{
              javaBindNum++;
              IrSearchVO.addWhereClause(" AND PACKAGE_STD_CD = :"+javaBindNum);
              IrSearchVO.setWhereClauseParam(javaBindNum-1,pkg.toUpperCase());
          }
        }
        if(corpCode!=null&&corpCode.trim().length()>0)
        {
          if(corpCode.contains("%"))
          {
            javaBindNum++;
            IrSearchVO.addWhereClause(" AND CORP_CD LIKE :"+javaBindNum);
            IrSearchVO.setWhereClauseParam(javaBindNum-1,corpCode.toUpperCase());
          }else{
              javaBindNum++;
              IrSearchVO.addWhereClause(" AND CORP_CD = :"+javaBindNum);
              IrSearchVO.setWhereClauseParam(javaBindNum-1,corpCode.toUpperCase());
          }
        }
        if(cust5code!=null&&cust5code.trim().length()>0)
        {
         if(cust5code.contains("%"))
         {
            javaBindNum++;
            //IrSearchVO.addWhereClause(" AND UPPER(RESERVTN_CUST_CD) LIKE UPPER(:"+javaBindNum+")");
            IrSearchVO.addWhereClause(" AND SOURCE_CODE LIKE :"+javaBindNum);
            IrSearchVO.setWhereClauseParam(javaBindNum-1,cust5code.toUpperCase());
         }else{
             javaBindNum++;
             //IrSearchVO.addWhereClause(" AND UPPER(RESERVTN_CUST_CD) LIKE UPPER(:"+javaBindNum+")");
             IrSearchVO.addWhereClause(" AND SOURCE_CODE = :"+javaBindNum);
             IrSearchVO.setWhereClauseParam(javaBindNum-1,cust5code.toUpperCase());
         }
        }

        if(javaBindNum>0)
        {
            IrSearchVO.executeQuery();
            utils.showMaxFecthSizeWarningMsg(getOADBTransaction(),"XXONGbwIrSearchVO1");
            IrSearchVO.setRangeStart(0);
            XXONGbwRecordsDisplayVOImpl recordsDisplayVO=getXXONGbwRecordsDisplayVO1();
            XXONGbwRecordsDisplayVORowImpl row1=(XXONGbwRecordsDisplayVORowImpl)recordsDisplayVO.first();
            row1.setAttribute("recCount",IrSearchVO.getRowCount()+" Record(s) found.");
        }else{
            throw new OAException("XXON","XXON_OM_GBW_SEARCH_ERR",
                                             null,
                                             OAException.ERROR,
                                             null);
        }
    }

    /**Container's getter for XXONGbwCorpCodeLovVO1
     */
    public XXONGbwCorpCodeLovVOImpl getXXONGbwCorpCodeLovVO1() {
        return (XXONGbwCorpCodeLovVOImpl)findViewObject("XXONGbwCorpCodeLovVO1");
    }

    /**Container's getter for XXONGbwCust5CodeLovVO1
     */
    public XXONGbwCust5CodeLovVOImpl getXXONGbwCust5CodeLovVO1() {
        return (XXONGbwCust5CodeLovVOImpl)findViewObject("XXONGbwCust5CodeLovVO1");
    }

    /**Container's getter for XXONGbwPtiLovVO1
     */
    public XXONGbwPtiLovVOImpl getXXONGbwPtiLovVO1() {
        return (XXONGbwPtiLovVOImpl)findViewObject("XXONGbwPtiLovVO1");
    }

    /**Container's getter for XXONGbwPackageLovVO1
     */
    public XXONGbwPackageLovVOImpl getXXONGbwPackageLovVO1() {
        return (XXONGbwPackageLovVOImpl)findViewObject("XXONGbwPackageLovVO1");
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("oracle.apps.xxon.om.gbw.invres.server", /* package name */
      "XXONGbwIrSearchAMLocal" /* Configuration Name */);
    }

    /**Container's getter for XXONGbwIrSearchVO1
     */
    public XXONGbwIrSearchVOImpl getXXONGbwIrSearchVO1() {
        return (XXONGbwIrSearchVOImpl)findViewObject("XXONGbwIrSearchVO1");
    }

    /**Container's getter for XXONGbwIrSerachValuesVO1
     */
    public XXONGbwIrSerachValuesVOImpl getXXONGbwIrSerachValuesVO1() {
        return (XXONGbwIrSerachValuesVOImpl)findViewObject("XXONGbwIrSerachValuesVO1");
    }

    /**Container's getter for XXONGbwRecordsDisplayVO1
     */
    public XXONGbwRecordsDisplayVOImpl getXXONGbwRecordsDisplayVO1() {
        return (XXONGbwRecordsDisplayVOImpl)findViewObject("XXONGbwRecordsDisplayVO1");
    }
}
