package oracle.apps.xxon.om.gbw.invres.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwIrSerachValuesVORowImpl extends OAViewRowImpl {

    public static final int DUMMY = 0;
    public static final int OPN = 1;
    public static final int CORPCODE = 2;
    public static final int CUST5CODE = 3;
    public static final int PKG = 4;
    public static final int PAL = 5;
    public static final int SOURCEITEM = 6;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwIrSerachValuesVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Dummy
     */
    public void setDummy(String value) {
        setAttributeInternal(DUMMY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            return getDummy();
        case OPN:
            return getOPN();
        case CORPCODE:
            return getCorpCode();
        case CUST5CODE:
            return getCust5Code();
        case PKG:
            return getpkg();
        case PAL:
            return getpal();
        case SOURCEITEM:
            return getsourceItem();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            setDummy((String)value);
            return;
        case OPN:
            setOPN((String)value);
            return;
        case CORPCODE:
            setCorpCode((String)value);
            return;
        case CUST5CODE:
            setCust5Code((String)value);
            return;
        case PKG:
            setpkg((String)value);
            return;
        case PAL:
            setpal((String)value);
            return;
        case SOURCEITEM:
            setsourceItem((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute OPN
     */
    public String getOPN() {
        return (String) getAttributeInternal(OPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OPN
     */
    public void setOPN(String value) {
        setAttributeInternal(OPN, value);
    }

    /**Gets the attribute value for the calculated attribute CorpCode
     */
    public String getCorpCode() {
        return (String) getAttributeInternal(CORPCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CorpCode
     */
    public void setCorpCode(String value) {
        setAttributeInternal(CORPCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Cust5Code
     */
    public String getCust5Code() {
        return (String) getAttributeInternal(CUST5CODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cust5Code
     */
    public void setCust5Code(String value) {
        setAttributeInternal(CUST5CODE, value);
    }

    /**Gets the attribute value for the calculated attribute pkg
     */
    public String getpkg() {
        return (String) getAttributeInternal(PKG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute pkg
     */
    public void setpkg(String value) {
        setAttributeInternal(PKG, value);
    }

    /**Gets the attribute value for the calculated attribute pal
     */
    public String getpal() {
        return (String) getAttributeInternal(PAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute pal
     */
    public void setpal(String value) {
        setAttributeInternal(PAL, value);
    }

    /**Gets the attribute value for the calculated attribute sourceItem
     */
    public String getsourceItem() {
        return (String) getAttributeInternal(SOURCEITEM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute sourceItem
     */
    public void setsourceItem(String value) {
        setAttributeInternal(SOURCEITEM, value);
    }
}
