package oracle.apps.xxon.om.gbw.invres.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwIrSearchVORowImpl extends OAViewRowImpl {
    public static final int MPN = 0;
    public static final int PTI4 = 1;
    public static final int PACKAGESTDCD = 2;
    public static final int CORPCD = 3;
    public static final int RESERVTNCUSTCD = 4;
    public static final int REQUESTDATE = 5;
    public static final int SCHEDULESHIPDATE = 6;
    public static final int BALANCEQUANTITY = 7;
    public static final int CREATIONDATE = 8;
    public static final int LASTUPDATEDATE = 9;
    public static final int HEADERNUMBER = 10;
    public static final int RESERVTNWKENDDATE = 11;
    public static final int PLANNEDDLVRYDATE = 12;
    public static final int CPN = 13;
    public static final int INITIALQUANTITY = 14;
    public static final int SSFACILITYLOCCD = 15;
    public static final int SCHRETURNCD = 16;
    public static final int RELEASEDATE = 17;
    public static final int WORKWEEKNUM = 18;
    public static final int TRANSMITDAYOFWK = 19;
    public static final int RESERVTNTYPE = 20;
    public static final int CREATEDBY = 21;
    public static final int LASTUPDATEDBY = 22;
    public static final int LASTUPDATELOGIN = 23;
    public static final int DEMANDTYPE = 24;
    public static final int SOURCECODE = 25;
    public static final int SITEUSECODE = 26;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwIrSearchVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Mpn
     */
    public String getMpn() {
        return (String) getAttributeInternal(MPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Mpn
     */
    public void setMpn(String value) {
        setAttributeInternal(MPN, value);
    }

    /**Gets the attribute value for the calculated attribute HeaderNumber
     */
    public String getHeaderNumber() {
        return (String) getAttributeInternal(HEADERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute HeaderNumber
     */
    public void setHeaderNumber(String value) {
        setAttributeInternal(HEADERNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute Pti4
     */
    public String getPti4() {
        return (String) getAttributeInternal(PTI4);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pti4
     */
    public void setPti4(String value) {
        setAttributeInternal(PTI4, value);
    }

    /**Gets the attribute value for the calculated attribute PackageStdCd
     */
    public String getPackageStdCd() {
        return (String) getAttributeInternal(PACKAGESTDCD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PackageStdCd
     */
    public void setPackageStdCd(String value) {
        setAttributeInternal(PACKAGESTDCD, value);
    }

    /**Gets the attribute value for the calculated attribute CorpCd
     */
    public String getCorpCd() {
        return (String) getAttributeInternal(CORPCD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CorpCd
     */
    public void setCorpCd(String value) {
        setAttributeInternal(CORPCD, value);
    }

    /**Gets the attribute value for the calculated attribute ReservtnCustCd
     */
    public String getReservtnCustCd() {
        return (String) getAttributeInternal(RESERVTNCUSTCD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReservtnCustCd
     */
    public void setReservtnCustCd(String value) {
        setAttributeInternal(RESERVTNCUSTCD, value);
    }

    /**Gets the attribute value for the calculated attribute ScheduleShipDate
     */
    public Date getScheduleShipDate() {
        return (Date) getAttributeInternal(SCHEDULESHIPDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ScheduleShipDate
     */
    public void setScheduleShipDate(Date value) {
        setAttributeInternal(SCHEDULESHIPDATE, value);
    }

    /**Gets the attribute value for the calculated attribute BalanceQuantity
     */
    public Number getBalanceQuantity() {
        return (Number) getAttributeInternal(BALANCEQUANTITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BalanceQuantity
     */
    public void setBalanceQuantity(Number value) {
        setAttributeInternal(BALANCEQUANTITY, value);
    }

    /**Gets the attribute value for the calculated attribute ReservtnWkEndDate
     */
    public Date getReservtnWkEndDate() {
        return (Date) getAttributeInternal(RESERVTNWKENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReservtnWkEndDate
     */
    public void setReservtnWkEndDate(Date value) {
        setAttributeInternal(RESERVTNWKENDDATE, value);
    }

    /**Gets the attribute value for the calculated attribute RequestDate
     */
    public Date getRequestDate() {
        return (Date) getAttributeInternal(REQUESTDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RequestDate
     */
    public void setRequestDate(Date value) {
        setAttributeInternal(REQUESTDATE, value);
    }

    /**Gets the attribute value for the calculated attribute PlannedDlvryDate
     */
    public Date getPlannedDlvryDate() {
        return (Date) getAttributeInternal(PLANNEDDLVRYDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PlannedDlvryDate
     */
    public void setPlannedDlvryDate(Date value) {
        setAttributeInternal(PLANNEDDLVRYDATE, value);
    }

    /**Gets the attribute value for the calculated attribute Cpn
     */
    public String getCpn() {
        return (String) getAttributeInternal(CPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cpn
     */
    public void setCpn(String value) {
        setAttributeInternal(CPN, value);
    }

    /**Gets the attribute value for the calculated attribute InitialQuantity
     */
    public Number getInitialQuantity() {
        return (Number) getAttributeInternal(INITIALQUANTITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InitialQuantity
     */
    public void setInitialQuantity(Number value) {
        setAttributeInternal(INITIALQUANTITY, value);
    }

    /**Gets the attribute value for the calculated attribute SsFacilityLocCd
     */
    public String getSsFacilityLocCd() {
        return (String) getAttributeInternal(SSFACILITYLOCCD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SsFacilityLocCd
     */
    public void setSsFacilityLocCd(String value) {
        setAttributeInternal(SSFACILITYLOCCD, value);
    }

    /**Gets the attribute value for the calculated attribute SchReturnCd
     */
    public String getSchReturnCd() {
        return (String) getAttributeInternal(SCHRETURNCD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SchReturnCd
     */
    public void setSchReturnCd(String value) {
        setAttributeInternal(SCHRETURNCD, value);
    }

    /**Gets the attribute value for the calculated attribute ReleaseDate
     */
    public Date getReleaseDate() {
        return (Date) getAttributeInternal(RELEASEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReleaseDate
     */
    public void setReleaseDate(Date value) {
        setAttributeInternal(RELEASEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute WorkWeekNum
     */
    public String getWorkWeekNum() {
        return (String) getAttributeInternal(WORKWEEKNUM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WorkWeekNum
     */
    public void setWorkWeekNum(String value) {
        setAttributeInternal(WORKWEEKNUM, value);
    }

    /**Gets the attribute value for the calculated attribute TransmitDayOfWk
     */
    public String getTransmitDayOfWk() {
        return (String) getAttributeInternal(TRANSMITDAYOFWK);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TransmitDayOfWk
     */
    public void setTransmitDayOfWk(String value) {
        setAttributeInternal(TRANSMITDAYOFWK, value);
    }

    /**Gets the attribute value for the calculated attribute ReservtnType
     */
    public String getReservtnType() {
        return (String) getAttributeInternal(RESERVTNTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReservtnType
     */
    public void setReservtnType(String value) {
        setAttributeInternal(RESERVTNTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute DemandType
     */
    public String getDemandType() {
        return (String) getAttributeInternal(DEMANDTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DemandType
     */
    public void setDemandType(String value) {
        setAttributeInternal(DEMANDTYPE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case MPN:
            return getMpn();
        case PTI4:
            return getPti4();
        case PACKAGESTDCD:
            return getPackageStdCd();
        case CORPCD:
            return getCorpCd();
        case RESERVTNCUSTCD:
            return getReservtnCustCd();
        case REQUESTDATE:
            return getRequestDate();
        case SCHEDULESHIPDATE:
            return getScheduleShipDate();
        case BALANCEQUANTITY:
            return getBalanceQuantity();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case HEADERNUMBER:
            return getHeaderNumber();
        case RESERVTNWKENDDATE:
            return getReservtnWkEndDate();
        case PLANNEDDLVRYDATE:
            return getPlannedDlvryDate();
        case CPN:
            return getCpn();
        case INITIALQUANTITY:
            return getInitialQuantity();
        case SSFACILITYLOCCD:
            return getSsFacilityLocCd();
        case SCHRETURNCD:
            return getSchReturnCd();
        case RELEASEDATE:
            return getReleaseDate();
        case WORKWEEKNUM:
            return getWorkWeekNum();
        case TRANSMITDAYOFWK:
            return getTransmitDayOfWk();
        case RESERVTNTYPE:
            return getReservtnType();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case DEMANDTYPE:
            return getDemandType();
        case SOURCECODE:
            return getSourceCode();
        case SITEUSECODE:
            return getSiteUseCode();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case MPN:
            setMpn((String)value);
            return;
        case PTI4:
            setPti4((String)value);
            return;
        case PACKAGESTDCD:
            setPackageStdCd((String)value);
            return;
        case CORPCD:
            setCorpCd((String)value);
            return;
        case RESERVTNCUSTCD:
            setReservtnCustCd((String)value);
            return;
        case REQUESTDATE:
            setRequestDate((Date)value);
            return;
        case SCHEDULESHIPDATE:
            setScheduleShipDate((Date)value);
            return;
        case BALANCEQUANTITY:
            setBalanceQuantity((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case HEADERNUMBER:
            setHeaderNumber((String)value);
            return;
        case RESERVTNWKENDDATE:
            setReservtnWkEndDate((Date)value);
            return;
        case PLANNEDDLVRYDATE:
            setPlannedDlvryDate((Date)value);
            return;
        case CPN:
            setCpn((String)value);
            return;
        case INITIALQUANTITY:
            setInitialQuantity((Number)value);
            return;
        case SSFACILITYLOCCD:
            setSsFacilityLocCd((String)value);
            return;
        case SCHRETURNCD:
            setSchReturnCd((String)value);
            return;
        case RELEASEDATE:
            setReleaseDate((Date)value);
            return;
        case WORKWEEKNUM:
            setWorkWeekNum((String)value);
            return;
        case TRANSMITDAYOFWK:
            setTransmitDayOfWk((String)value);
            return;
        case RESERVTNTYPE:
            setReservtnType((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case DEMANDTYPE:
            setDemandType((String)value);
            return;
        case SOURCECODE:
            setSourceCode((String)value);
            return;
        case SITEUSECODE:
            setSiteUseCode((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute SourceCode
     */
    public String getSourceCode() {
        return (String) getAttributeInternal(SOURCECODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SourceCode
     */
    public void setSourceCode(String value) {
        setAttributeInternal(SOURCECODE, value);
    }

    /**Gets the attribute value for the calculated attribute SiteUseCode
     */
    public String getSiteUseCode() {
        return (String) getAttributeInternal(SITEUSECODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SiteUseCode
     */
    public void setSiteUseCode(String value) {
        setAttributeInternal(SITEUSECODE, value);
    }
}
