package oracle.apps.xxon.om.gbw.popup.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.xxon.om.gbw.util.XXONGbwUtil;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwPopupAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public XXONGbwPopupAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("oracle.apps.xxon.om.gbw.popup.server", /* package name */
      "XXONGbwPopupAMLocal" /* Configuration Name */);
    }
 public void initItemVO(String OrganizationId,String InventoryItemId,String opn)
 {
     log("initItemVO:: OrganizationId-->"+OrganizationId);
     log("initItemVO:: InventoryItemId-->"+InventoryItemId);
     log("initItemVO:: opn-->"+opn);
     XXONGbwOpnItemDetailsVOImpl ItemDetailsVO=getXXONGbwOpnItemDetailsVO1();
     ItemDetailsVO.setWhereClauseParams(null);
     ItemDetailsVO.setWhereClause("1=1");     
     int javaBindNum=0;
     if(opn!=null&&opn.trim().length()>0)
     {
        javaBindNum++;         
        ItemDetailsVO.addWhereClause(" AND OPN=:"+javaBindNum+"");
        ItemDetailsVO.setWhereClauseParam(javaBindNum-1,opn);
     }
     if(InventoryItemId!=null&&InventoryItemId.trim().length()>0)
     {
        javaBindNum++;         
        ItemDetailsVO.addWhereClause(" AND INVENTORY_ITEM_ID=:"+javaBindNum+"");
        ItemDetailsVO.setWhereClauseParam(javaBindNum-1,InventoryItemId);
     }
     
     if(javaBindNum>0)
     {
      ItemDetailsVO.executeQuery();
     }
 
 }
 public void initHoldVO(String HeaderId,String LineId)
 {
     XXONGbwOrderHoldDetailsVOImpl HoldDetailsVO=getXXONGbwOrderHoldDetailsVO1();
     HoldDetailsVO.setWhereClauseParams(null);
     HoldDetailsVO.setWhereClauseParam(0,LineId);
     HoldDetailsVO.executeQuery();
 }
 
 public void initCustomerDetailsVO(String site_use_code,String cust5code) 
 {
     XXONGbwCustomerDetailsVOImpl custdetailsvo = getXXONGbwCustomerDetailsVO1();
     custdetailsvo.setWhereClauseParams(null);
     custdetailsvo.setWhereClause(null);
     custdetailsvo.setWhereClause("1=1");  
     int javaBindNum=0;
     if(site_use_code!=null&&site_use_code.trim().length()>0)
     {
        javaBindNum++;         
        custdetailsvo.addWhereClause(" AND SITE_USE_CODE=:"+javaBindNum+"");
        custdetailsvo.setWhereClauseParam(javaBindNum-1,site_use_code);
     }
     if(cust5code!=null&&cust5code.trim().length()>0)
     {
        javaBindNum++;         
        custdetailsvo.addWhereClause(" AND CUST_CODE=:"+javaBindNum+"");
        custdetailsvo.setWhereClauseParam(javaBindNum-1,cust5code);
     }     
     if(javaBindNum>0)
     {
      custdetailsvo.executeQuery();
     }
 }
 
 
   
    /**
     * Below Method is to print the log messages
     *@param Message for text 
    */
    private void log(String Message)
    {
        XXONGbwUtil utils= new XXONGbwUtil();
        OADBTransaction oadb=getOADBTransaction();
        utils.log(Message,oadb);
    }

    /**Container's getter for XXONGbwOpnItemDetailsVO1
     */
    public XXONGbwOpnItemDetailsVOImpl getXXONGbwOpnItemDetailsVO1() {
        return (XXONGbwOpnItemDetailsVOImpl)findViewObject("XXONGbwOpnItemDetailsVO1");
    }

    /**Container's getter for XXONGbwOrderHoldDetailsVO1
     */
    public XXONGbwOrderHoldDetailsVOImpl getXXONGbwOrderHoldDetailsVO1() {
        return (XXONGbwOrderHoldDetailsVOImpl)findViewObject("XXONGbwOrderHoldDetailsVO1");
    }

    /**Container's getter for XXONGbwCustomerDetailsVO1
     */
    public XXONGbwCustomerDetailsVOImpl getXXONGbwCustomerDetailsVO1() {
        return (XXONGbwCustomerDetailsVOImpl)findViewObject("XXONGbwCustomerDetailsVO1");
    }
}
