package oracle.apps.xxon.om.gbw.baklogview.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwSearchCriteriaValuesVORowImpl extends OAViewRowImpl {
    public static final int DUMMY = 0;
    public static final int OPN = 1;
    public static final int PKG = 2;
    public static final int PAL = 3;
    public static final int CORPCODE = 4;
    public static final int CUST5CODE = 5;
    public static final int ORDERNUMBER = 6;
    public static final int DEMANDBANK = 7;
    public static final int COI = 8;
    public static final int CONSUMPTION = 9;
    public static final int SAMPLESORDERS = 10;
    public static final int OPUNIT = 11;
    public static final int UNSCHEDULEDDEMANDS = 12;
    public static final int MISMATCHEDDEMANDS = 13;
    public static final int REPLENISORDERS = 14;
    public static final int ORGID = 15;
    public static final int ORDERTYPE = 16;
    public static final int LEGACYSO = 17;
    public static final int LINENUMBER = 18;
    public static final int DATERANGE = 19;
    public static final int PONUMBER = 20;
    public static final int EXCLUDEFR = 21;
    public static final int SCHEDULEDDEMANDS = 22;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwSearchCriteriaValuesVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Dummy
     */
    public void setDummy(String value) {
        setAttributeInternal(DUMMY, value);
    }

    /**Gets the attribute value for the calculated attribute Opn
     */
    public String getOpn() {
        return (String) getAttributeInternal(OPN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Opn
     */
    public void setOpn(String value) {
        setAttributeInternal(OPN, value);
    }

    /**Gets the attribute value for the calculated attribute Pkg
     */
    public String getPkg() {
        return (String) getAttributeInternal(PKG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pkg
     */
    public void setPkg(String value) {
        setAttributeInternal(PKG, value);
    }

    /**Gets the attribute value for the calculated attribute Pal
     */
    public String getPal() {
        return (String) getAttributeInternal(PAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pal
     */
    public void setPal(String value) {
        setAttributeInternal(PAL, value);
    }


    /**Gets the attribute value for the calculated attribute OrderNumber
     */
    public String getOrderNumber() {
        return (String) getAttributeInternal(ORDERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderNumber
     */
    public void setOrderNumber(String value) {
        setAttributeInternal(ORDERNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute DemandBank
     */
    public String getDemandBank() {
        return (String) getAttributeInternal(DEMANDBANK);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DemandBank
     */
    public void setDemandBank(String value) {
        setAttributeInternal(DEMANDBANK, value);
    }

    /**Gets the attribute value for the calculated attribute Coi
     */
    public String getCoi() {
        return (String) getAttributeInternal(COI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Coi
     */
    public void setCoi(String value) {
        setAttributeInternal(COI, value);
    }

    /**Gets the attribute value for the calculated attribute Consumption
     */
    public String getConsumption() {
        return (String) getAttributeInternal(CONSUMPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Consumption
     */
    public void setConsumption(String value) {
        setAttributeInternal(CONSUMPTION, value);
    }

    /**Gets the attribute value for the calculated attribute SamplesOrders
     */
    public String getSamplesOrders() {
        return (String) getAttributeInternal(SAMPLESORDERS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SamplesOrders
     */
    public void setSamplesOrders(String value) {
        setAttributeInternal(SAMPLESORDERS, value);
    }

    /**Gets the attribute value for the calculated attribute OpUnit
     */
    public String getOpUnit() {
        return (String) getAttributeInternal(OPUNIT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OpUnit
     */
    public void setOpUnit(String value) {
        setAttributeInternal(OPUNIT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            return getDummy();
        case OPN:
            return getOpn();
        case PKG:
            return getPkg();
        case PAL:
            return getPal();
        case CORPCODE:
            return getCorpCode();
        case CUST5CODE:
            return getCust5Code();
        case ORDERNUMBER:
            return getOrderNumber();
        case DEMANDBANK:
            return getDemandBank();
        case COI:
            return getCoi();
        case CONSUMPTION:
            return getConsumption();
        case SAMPLESORDERS:
            return getSamplesOrders();
        case OPUNIT:
            return getOpUnit();
        case UNSCHEDULEDDEMANDS:
            return getUnscheduledDemands();
        case MISMATCHEDDEMANDS:
            return getMismatchedDemands();
        case REPLENISORDERS:
            return getreplenisorders();
        case ORGID:
            return getOrgId();
        case ORDERTYPE:
            return getOrderType();
        case LEGACYSO:
            return getlegacySo();
        case LINENUMBER:
            return getlineNumber();
        case DATERANGE:
            return getDateRange();
        case PONUMBER:
            return getPoNumber();
        case EXCLUDEFR:
            return getExcludeFr();
        case SCHEDULEDDEMANDS:
            return getScheduledDemands();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DUMMY:
            setDummy((String)value);
            return;
        case OPN:
            setOpn((String)value);
            return;
        case PKG:
            setPkg((String)value);
            return;
        case PAL:
            setPal((String)value);
            return;
        case CORPCODE:
            setCorpCode((String)value);
            return;
        case CUST5CODE:
            setCust5Code((String)value);
            return;
        case ORDERNUMBER:
            setOrderNumber((String)value);
            return;
        case DEMANDBANK:
            setDemandBank((String)value);
            return;
        case COI:
            setCoi((String)value);
            return;
        case CONSUMPTION:
            setConsumption((String)value);
            return;
        case SAMPLESORDERS:
            setSamplesOrders((String)value);
            return;
        case OPUNIT:
            setOpUnit((String)value);
            return;
        case UNSCHEDULEDDEMANDS:
            setUnscheduledDemands((String)value);
            return;
        case MISMATCHEDDEMANDS:
            setMismatchedDemands((String)value);
            return;
        case REPLENISORDERS:
            setreplenisorders((String)value);
            return;
        case ORGID:
            setOrgId((String)value);
            return;
        case ORDERTYPE:
            setOrderType((String)value);
            return;
        case LEGACYSO:
            setlegacySo((String)value);
            return;
        case LINENUMBER:
            setlineNumber((String)value);
            return;
        case DATERANGE:
            setDateRange((String)value);
            return;
        case PONUMBER:
            setPoNumber((String)value);
            return;
        case EXCLUDEFR:
            setExcludeFr((String)value);
            return;
        case SCHEDULEDDEMANDS:
            setScheduledDemands((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute UnscheduledDemands
     */
    public String getUnscheduledDemands() {
        return (String) getAttributeInternal(UNSCHEDULEDDEMANDS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UnscheduledDemands
     */
    public void setUnscheduledDemands(String value) {
        setAttributeInternal(UNSCHEDULEDDEMANDS, value);
    }

    /**Gets the attribute value for the calculated attribute MismatchedDemands
     */
    public String getMismatchedDemands() {
        return (String) getAttributeInternal(MISMATCHEDDEMANDS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MismatchedDemands
     */
    public void setMismatchedDemands(String value) {
        setAttributeInternal(MISMATCHEDDEMANDS, value);
    }

    /**Gets the attribute value for the calculated attribute replenisorders
     */
    public String getreplenisorders() {
        return (String) getAttributeInternal(REPLENISORDERS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute replenisorders
     */
    public void setreplenisorders(String value) {
        setAttributeInternal(REPLENISORDERS, value);
    }

    /**Gets the attribute value for the calculated attribute CorpCode
     */
    public String getCorpCode() {
        return (String) getAttributeInternal(CORPCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CorpCode
     */
    public void setCorpCode(String value) {
        setAttributeInternal(CORPCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Cust5Code
     */
    public String getCust5Code() {
        return (String) getAttributeInternal(CUST5CODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cust5Code
     */
    public void setCust5Code(String value) {
        setAttributeInternal(CUST5CODE, value);
    }

    /**Gets the attribute value for the calculated attribute OrgId
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrgId
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the attribute value for the calculated attribute OrderType
     */
    public String getOrderType() {
        return (String) getAttributeInternal(ORDERTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderType
     */
    public void setOrderType(String value) {
        setAttributeInternal(ORDERTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute legacySo
     */
    public String getlegacySo() {
        return (String) getAttributeInternal(LEGACYSO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute legacySo
     */
    public void setlegacySo(String value) {
        setAttributeInternal(LEGACYSO, value);
    }

    /**Gets the attribute value for the calculated attribute lineNumber
     */
    public String getlineNumber() {
        return (String) getAttributeInternal(LINENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute lineNumber
     */
    public void setlineNumber(String value) {
        setAttributeInternal(LINENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute DateRange
     */
    public String getDateRange() {
        return (String) getAttributeInternal(DATERANGE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DateRange
     */
    public void setDateRange(String value) {
        setAttributeInternal(DATERANGE, value);
    }

    /**Gets the attribute value for the calculated attribute PoNumber
     */
    public String getPoNumber() {
        return (String) getAttributeInternal(PONUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PoNumber
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute ExcludeFr
     */
    public String getExcludeFr() {
        return (String) getAttributeInternal(EXCLUDEFR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ExcludeFr
     */
    public void setExcludeFr(String value) {
        setAttributeInternal(EXCLUDEFR, value);
    }

    /**Gets the attribute value for the calculated attribute ScheduledDemands
     */
    public String getScheduledDemands() {
        return (String) getAttributeInternal(SCHEDULEDDEMANDS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ScheduledDemands
     */
    public void setScheduledDemands(String value) {
        setAttributeInternal(SCHEDULEDDEMANDS, value);
    }
}
