package oracle.apps.xxon.om.gbw.baklogview.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwGetRlagFalgCountVORowImpl extends OAViewRowImpl {

    public static final int RELEASEDFLAGCOUNT = 0;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwGetRlagFalgCountVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute ReleasedFlagCount
     */
    public Number getReleasedFlagCount() {
        return (Number) getAttributeInternal(RELEASEDFLAGCOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReleasedFlagCount
     */
    public void setReleasedFlagCount(Number value) {
        setAttributeInternal(RELEASEDFLAGCOUNT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RELEASEDFLAGCOUNT:
            return getReleasedFlagCount();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RELEASEDFLAGCOUNT:
            setReleasedFlagCount((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
