package oracle.apps.xxon.om.gbw.baklogview.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXONGbwGetRespKeyVORowImpl extends OAViewRowImpl {
    public static final int RESPONSIBILITYKEY = 0;

    /**This is the default constructor (do not remove)
     */
    public XXONGbwGetRespKeyVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute ResponsibilityKey
     */
    public String getResponsibilityKey() {
        return (String) getAttributeInternal(RESPONSIBILITYKEY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ResponsibilityKey
     */
    public void setResponsibilityKey(String value) {
        setAttributeInternal(RESPONSIBILITYKEY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RESPONSIBILITYKEY:
            return getResponsibilityKey();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RESPONSIBILITYKEY:
            setResponsibilityKey((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
